inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Style/StringLiterals:
  EnforcedStyle: single_quotes

Bundler/OrderedGems:
  Enabled: true

  Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/ToSWithArgument:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Layout/ElseAlignment:
  EnforcedStyleAlignWith: if